apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rkno
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-rkno@sha256:362fd6520faa5a318c2f32d93e7d05502765422c934b085b3bf07fa0830b30c7
        name: my-nodejs
        resources: {}
status: {}
